### ISSUE TITLE
In xfce4's file browser "Thunar" regular folders come up with whatever last style was applied.

### ISSUE THREAD

**Issue by chr15m** [daniruiz/Super-Flat-Remix#3]
Note the 'bin' and 'dev' folders here have a different icon theme.

![xfce4](https://cloud.githubusercontent.com/assets/67130/8694261/4e35415a-2b10-11e5-9282-0192fd5abda7.png)

**Comment by thomassross** [comment]
To fix this, `cd` to `~/.icons/Super Flat Remix/places/scalable` and run `ln -s folder.svg inode-directory.png`.

**Comment by chr15m** [comment]
Thanks! I submitted a PR #5 based on your fix.
