### ISSUE TITLE
Icon request: MusicBrainz Picard

### ISSUE THREAD

**Issue by MichaelTiebesl** [daniruiz/Super-Flat-Remix#7]
Is it possible to have an icon for MusicBrainz Picard?

[Desktop Entry]
Name=MusicBrainz Picard
Comment=Tag your music with the next generation MusicBrainz tagger
Exec=picard %F
Terminal=false
Type=Application
StartupNotify=true
Icon=picard
Categories=AudioVideo;Audio;AudioVideoEditing;
MimeType=audio/x-mp3;audio/ogg;audio/mpeg;application/ogg;audio/x-flac;audio/x-flac+ogg;audio/x-vorbis+ogg;audio/x-speex+ogg;audio/x-oggflac;audio/x-musepack;audio/x-tta;audio/x-ms-wma;audio/x-wavpack;
![picard](https://cloud.githubusercontent.com/assets/10792019/10270880/36700bd8-6b32-11e5-92a1-ec0544e9720f.png)

**Comment by MichaelTiebesl** [comment]
I already made the icon for picard. svg and png

![picard](https://cloud.githubusercontent.com/assets/10792019/10556990/7a9b8ee4-74ca-11e5-850d-f771a6769b31.png)

**Comment by daniruiz** [comment]
Mmmm.. I like it. I'll add it soon.

**Comment by MichaelTiebesl** [comment]
Thanks, just modified it if you want.
